name: DevSecOps AWS Pipeline

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: devsecops-app

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Trivy
      run: |
        sudo apt-get update
        sudo apt-get install -y wget gnupg lsb-release
        wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
        echo "deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main" | sudo tee /etc/apt/sources.list.d/trivy.list
        sudo apt-get update
        sudo apt-get install -y trivy

    - name: Scan Filesystem
      run: trivy fs . --severity HIGH,CRITICAL --exit-code 1

    - name: Build Docker Image
      run: docker build -t ${{ secrets.DOCKER_USER }}/${{ env.IMAGE_NAME }}:latest .

    - name: Scan Image
      run: trivy image ${{ secrets.DOCKER_USER }}/${{ env.IMAGE_NAME }}:latest --severity HIGH,CRITICAL --exit-code 1

    - name: Docker Login
      run: echo "${{ secrets.DOCKER_PASS }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin

    - name: Push Image
      run: docker push ${{ secrets.DOCKER_USER }}/${{ env.IMAGE_NAME }}:latest
